# Generated by Django 2.1.3 on 2018-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
                ('sobrenome', models.CharField(max_length=15)),
                ('dt_nascimento', models.DateTimeField()),
                ('nacionalidade', models.CharField(max_length=15)),
            ],
        ),
    ]
