# Generated by Django 2.1.3 on 2018-11-06 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20181105_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='endereco',
            fields=[
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='register.cliente')),
                ('cep', models.PositiveIntegerField()),
                ('rua', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Endereços Clientes',
            },
        ),
    ]
