# Generated by Django 2.1.3 on 2018-11-06 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20181106_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente', unique=True),
        ),
    ]
