# Generated by Django 2.1.3 on 2018-11-06 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20181106_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='clienteCobranca',
            fields=[
                ('numeroCartao', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('validade', models.CharField(max_length=5)),
                ('bandeiraCartao', models.CharField(max_length=25)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
            ],
            options={
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
