# Generated by Django 2.1.3 on 2018-11-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_clientecobranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='plano',
            fields=[
                ('idPlano', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.PositiveSmallIntegerField()),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
