# Generated by Django 2.1.3 on 2018-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20181107_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='idPlano',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plano',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
