# Generated by Django 2.1.3 on 2018-11-07 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20181107_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientePlano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.plano')),
            ],
            options={
                'verbose_name_plural': 'Planos dos clientes',
            },
        ),
    ]
