# Generated by Django 2.1.3 on 2018-11-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_clienteplano'),
    ]

    operations = [
        migrations.CreateModel(
            name='enderecoCobranca',
            fields=[
                ('cep', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='id',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
