# Generated by Django 2.1.3 on 2018-11-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20181107_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
