# Generated by Django 2.1.3 on 2018-11-08 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_endereco_bairro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enderecocobranca',
            options={'verbose_name_plural': 'Endereços Cobrança Clientes'},
        ),
        migrations.AddField(
            model_name='enderecocobranca',
            name='bairro',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='enderecocobranca',
            name='numeroCartao',
            field=models.ForeignKey(default='0000 0000 0000 0000', on_delete=django.db.models.deletion.CASCADE, to='register.clienteCobranca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enderecocobranca',
            name='rua',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
