# Generated by Django 2.1.3 on 2018-11-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20181108_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecocobranca',
            name='cidade',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='enderecocobranca',
            name='complemento',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='enderecocobranca',
            name='estado',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='enderecocobranca',
            name='numero',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enderecocobranca',
            name='pais',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
