# Generated by Django 2.1.3 on 2018-11-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20181108_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecocobranca',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='cidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='complemento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='pais',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='rua',
            field=models.CharField(default='', max_length=50),
        ),
    ]
