# Generated by Django 2.1.3 on 2018-11-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20181108_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='hub',
            fields=[
                ('idHub', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quantGuardaVolumes', models.PositiveIntegerField()),
                ('coordw', models.CharField(max_length=12)),
                ('coords', models.CharField(max_length=12)),
            ],
        ),
    ]
