# Generated by Django 2.1.3 on 2018-11-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='guardaVolume',
            fields=[
                ('num', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('capacidade', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('idHub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.hub')),
            ],
            options={
                'verbose_name_plural': 'Guarda Volumes',
            },
        ),
    ]
