# Generated by Django 2.1.3 on 2018-11-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_guardavolume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardavolume',
            old_name='capacidade',
            new_name='ocupacao',
        ),
    ]
