# Generated by Django 2.1.3 on 2018-11-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20181108_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('datahora', models.DateTimeField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=20)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
            ],
        ),
    ]
