# Generated by Django 2.1.3 on 2018-11-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='usa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraInicio', models.DateTimeField()),
                ('dataHoraFim', models.DateTimeField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.cliente')),
                ('idGuardaVolume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.guardaVolume')),
            ],
            options={
                'verbose_name_plural': 'Logs de usos',
            },
        ),
        migrations.RenameField(
            model_name='log',
            old_name='datahora',
            new_name='dataHora',
        ),
    ]
