# Generated by Django 2.1.3 on 2018-11-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_auto_20181108_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usa',
            options={'verbose_name_plural': 'Logs dos lockers'},
        ),
    ]
